name: 'setup-node-and-install-dependencies'
description: 'Setup Node and install dependencies'

runs:
  using: 'composite'
  steps:
    - name: Setup Node
      uses: actions/setup-node@v3
    - name: Setup cache
      uses: actions/cache@v3
      id: npm-cache
      with:
        path: ~/.npm
        key: npm-${{ hashFiles('**/package-lock.json') }}
    - name: Install dependencies
      shell: bash
      run: npm ci