name: 'Checkout, Install Node and Dependencies'
description: 'Install dependencies'

runs:
  using: 'composite'
  steps:
    - name: Checkout repository
      uses: actions/checkout@v3
    - name: Setup Node
      uses: actions/setup-node@v3
    - uses: actions/cache@v3
      id: npm-cache
      with:
        path: ~/.npm
        key: npm-${{ hashFiles('**/package-lock.json') }}
    - run: npm ci
      name: Install modules from npm