  name: Build and run unit tests

  on:
    push:
      branches: [main]
    pull_request:
      branches: [main]

  jobs:
    build:
      runs-on: ubuntu-latest

      steps:
        - name: Checkout repository
          uses: actions/checkout@v3
        - name: Setup Node
          uses: actions/setup-node@v3
        - run: npm ci
          name: Install modules from npm
        - run: npm run build
          name: Build
    unit-test:
      runs-on: ubuntu-latest

      steps:
        - name: Checkout repository
          uses: actions/checkout@v3
        - name: Setup Node
          uses: actions/setup-node@v3
        - run: npm ci
          name: Install modules from npm
        - run: npm test
          name: Run the tests