  name: Build and run unit tests

  on:
    push:
      branches: [main]
    pull_request:
      branches: [main]

  jobs:
    build:
      runs-on: ubuntu-latest

      steps:
        - name: Checkout and Setup Node
          uses: ./.github/actions/checkout-and-setup
        - run: npm run build
          name: Build
    unit-test:
      runs-on: ubuntu-latest

      steps:
        - name: Checkout and Setup Node
          uses: ./.github/actions/checkout-and-setup
        - run: npm test
          name: Run the tests
    coverage:
      runs-on: ubuntu-latest

      steps:
        - name: Checkout and Setup Node
          uses: ./.github/actions/checkout-and-setup
        - run: npm run coverage
          name: Generate coverage report
        - name: Upload coverage report
          uses: actions/upload-artifact@v3
          with:
            name: coverage-report
            path: coverage